// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApptqk_-ctH2g4Q9jz9i_qskIWZFfMiTc',
    appId: '1:504337660042:web:53081150818feae3469573',
    messagingSenderId: '504337660042',
    projectId: 'imessage-ff30d',
    authDomain: 'imessage-ff30d.firebaseapp.com',
    storageBucket: 'imessage-ff30d.appspot.com',
    measurementId: 'G-BPSDXWM9SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoGXhrPkL2X53xGiWebqYRcpdXy57OopQ',
    appId: '1:504337660042:android:1298857a528bb5e6469573',
    messagingSenderId: '504337660042',
    projectId: 'imessage-ff30d',
    storageBucket: 'imessage-ff30d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxmGbPP0sbBgQtGMeSHf1wRmrekHMX0MU',
    appId: '1:504337660042:ios:2fda1ce05415e7c6469573',
    messagingSenderId: '504337660042',
    projectId: 'imessage-ff30d',
    storageBucket: 'imessage-ff30d.appspot.com',
    iosBundleId: 'com.example.imessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxmGbPP0sbBgQtGMeSHf1wRmrekHMX0MU',
    appId: '1:504337660042:ios:eadc3d240e20391f469573',
    messagingSenderId: '504337660042',
    projectId: 'imessage-ff30d',
    storageBucket: 'imessage-ff30d.appspot.com',
    iosBundleId: 'com.example.imessage.RunnerTests',
  );
}
